#!/usr/bin/env bash
# This script is displaying "Best School" 9 times and Hi one time in 9th line
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++));
done
